metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata: ~
#  - add_cloud_metadata: ~
  - add_docker_metadata: ~
#  - add_kubernetes_metadata: ~

setup.template.enabled: true
setup.template.overwrite: true
setup.template.name: "metric-localhost"
setup.template.pattern: "metric-localhost-*"
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ["http://192.168.10.44:9201","http://192.168.10.44:9202","http://192.168.10.44:9203"]
  index: "metric-localhost-%{+yyyy.MM.dd}"
  worker: 2

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["http://192.168.10.44:9201","http://192.168.10.44:9202","http://192.168.10.44:9203"]

