cluster.name: "elk"

node.name: node2
node.master: false
node.data: true

network.bind_host: 0.0.0.0
network.publish_host: 192.168.10.24 

http.port: 9202
transport.tcp.port: 9302

http.cors.enabled: true
http.cors.allow-origin: "*"

discovery.seed_hosts: ["192.168.10.24:9300","192.168.10.24:9301","192.168.10.24:9302"]
cluster.initial_master_nodes: ["node1"]
